# Generated by Django 3.1.8 on 2021-08-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmark',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
